const state={data:[],current:new Date(new Date().getFullYear(),new Date().getMonth(),1),filters:{search:"",country:"",type:""}};
const $=id=>document.getElementById(id);
const YEAR=new Date().getFullYear();
const fmtMonth=new Intl.DateTimeFormat("es-CO",{month:"long"});
const MONTHS=["Ene","Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"];
const unique=v=>[...new Set(v.filter(Boolean))].sort((a,b)=>a.localeCompare(b,"es"));
const esc=v=>String(v??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[ch]));
function filtered(){const f=state.filters;return state.data.filter(e=>{const h=[e.name,e.country,e.type,e.rectors?.[String(YEAR)]].filter(Boolean).join(" ").toLowerCase();return(!f.search||h.includes(f.search.toLowerCase()))&&(!f.country||e.country===f.country)&&(!f.type||e.type===f.type)})}
function anniversary(e){return YEAR-e.foundation_year}
function context(e){return [e.country,`${anniversary(e)} años en ${YEAR}`].join(" · ")}
function fillFilters(){unique(state.data.map(e=>e.country)).forEach(v=>$("countryFilter").insertAdjacentHTML("beforeend",`<option value="${esc(v)}">${esc(v)}</option>`));unique(state.data.map(e=>e.type)).forEach(v=>$("typeFilter").insertAdjacentHTML("beforeend",`<option value="${esc(v)}">${esc(v)}</option>`))}
function renderStats(){const now=new Date(),m=now.getMonth()+1,d=now.getDate();$("statInstitutions").textContent=state.data.length;$("statCountries").textContent=unique(state.data.map(e=>e.country)).length;$("statMonth").textContent=state.data.filter(e=>e.month===m).length;const upcoming=state.data.map(e=>({...e,delta:(new Date(YEAR,e.month-1,e.day)-new Date(YEAR,now.getMonth(),now.getDate()))/86400000})).filter(e=>e.delta>=0).sort((a,b)=>a.delta-b.delta||a.name.localeCompare(b.name,"es"))[0];$("statNext").textContent=upcoming?`${upcoming.day} ${MONTHS[upcoming.month-1]}`:"—"}
function renderCalendar(){const m=state.current.getMonth(),ev=filtered().filter(e=>e.month===m+1);$("monthTitle").textContent=`${fmtMonth.format(state.current)} ${YEAR}`;$("monthSubtitle").textContent=`${ev.length} efeméride${ev.length===1?"":"s"} registrada${ev.length===1?"":"s"} en este mes`;const first=new Date(YEAR,m,1),last=new Date(YEAR,m+1,0),idx=(first.getDay()+6)%7,cells=Math.ceil((idx+last.getDate())/7)*7,start=new Date(YEAR,m,1-idx);let html="";for(let i=0;i<cells;i++){const d=new Date(start);d.setDate(start.getDate()+i);const outside=d.getMonth()!==m;const dayEvents=outside?[]:ev.filter(e=>e.day===d.getDate());html+=`<div class="day ${outside?"outside":""}"><div class="day-number">${d.getDate()}</div>`;dayEvents.slice(0,3).forEach(e=>html+=`<button class="event-chip" data-name="${esc(e.name)}"><span class="event-chip-title">${esc(e.name)}</span><span class="event-chip-meta">${esc(e.country)} · ${anniversary(e)} años</span></button>`);if(dayEvents.length>3)html+=`<div class="more">+${dayEvents.length-3} más</div>`;html+="</div>"}$("calendar").innerHTML=html;document.querySelectorAll("[data-name]").forEach(b=>b.addEventListener("click",()=>openEvent(b.dataset.name)))}
function renderList(){const m=state.current.getMonth()+1,ev=filtered().filter(e=>e.month===m).sort((a,b)=>a.day-b.day||a.name.localeCompare(b.name,"es"));$("monthList").innerHTML=ev.length?ev.map(e=>`<article class="event-row"><div class="event-date">${String(e.day).padStart(2,"0")} ${MONTHS[e.month-1]}</div><div><h3>${esc(e.name)}</h3><p>${esc(context(e))}</p><span class="country">${esc(e.type)}</span></div><button data-name="${esc(e.name)}">Ver ficha</button></article>`).join(""):'<p class="empty">No hay efemérides para los filtros seleccionados en este mes.</p>';document.querySelectorAll("#monthList [data-name]").forEach(b=>b.addEventListener("click",()=>openEvent(b.dataset.name)))}
function openEvent(name){const e=state.data.find(x=>x.name===name);if(!e)return;const date=new Intl.DateTimeFormat("es-CO",{day:"numeric",month:"long"}).format(new Date(2000,e.month-1,e.day));const r26=e.rectors?.["2026"]||"Pendiente",r27=e.rectors?.["2027"]||"Pendiente",r28=e.rectors?.["2028"]||"Pendiente";$("dialogContent").innerHTML=`<p class="eyebrow">${esc(e.country)} · ${esc(e.type)}</p><h2>${esc(e.name)}</h2><p>Fecha fundacional registrada: <strong>${esc(date)} de ${e.foundation_year}</strong></p><div class="detail-meta"><div><small>Año de fundación</small>${e.foundation_year}</div><div><small>Aniversario en ${YEAR}</small>${anniversary(e)} años</div><div><small>Rector / autoridad 2026</small>${esc(r26)}</div><div><small>Rector / autoridad 2027</small>${esc(r27)}</div><div><small>Rector / autoridad 2028</small>${esc(r28)}</div><div><small>País / ámbito</small>${esc(e.country)}</div></div>`;$("detailDialog").showModal()}
function renderAll(){renderCalendar();renderList()}
function icsEscape(v){return String(v??"").replace(/\\/g,"\\\\").replace(/,/g,"\\,").replace(/;/g,"\\;").replace(/\n/g,"\\n")}
function downloadICS(){const stamp=new Date().toISOString().replace(/[-:]/g,"").replace(/\.\d{3}Z$/,"Z"),lines=["BEGIN:VCALENDAR","VERSION:2.0","PRODID:-//Efemerides Universitarias//ES","CALSCALE:GREGORIAN"];filtered().forEach(e=>{const mm=String(e.month).padStart(2,"0"),dd=String(e.day).padStart(2,"0");lines.push("BEGIN:VEVENT",`UID:${e.foundation_year}-${e.month}-${e.day}-${encodeURIComponent(e.name)}@efemerides-universitarias`,`DTSTAMP:${stamp}`,`DTSTART;VALUE=DATE:${YEAR}${mm}${dd}`,"RRULE:FREQ=YEARLY",`SUMMARY:${icsEscape(e.name)}`,`DESCRIPTION:${icsEscape(`Fundación: ${e.foundation_year} | ${e.country} | ${e.type}`)}`,"END:VEVENT")});lines.push("END:VCALENDAR");const blob=new Blob([lines.join("\r\n")],{type:"text/calendar;charset=utf-8"}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download="efemerides-universitarias.ics";a.click();URL.revokeObjectURL(url)}
async function init(){const res=await fetch("https://raw.githubusercontent.com/williamsjimenez/efemerides_nuestras/main/data/universidades.json?v="+Date.now(),{cache:"no-store"});if(!res.ok)throw new Error("No se pudo cargar el repositorio de efemérides");const raw=await res.json();state.data=raw.institutions||[];fillFilters();renderStats();$("searchInput").addEventListener("input",e=>{state.filters.search=e.target.value.trim();renderAll()});$("countryFilter").addEventListener("change",e=>{state.filters.country=e.target.value;renderAll()});$("typeFilter").addEventListener("change",e=>{state.filters.type=e.target.value;renderAll()});$("prevMonth").addEventListener("click",()=>{state.current=new Date(YEAR,(state.current.getMonth()+11)%12,1);renderAll()});$("nextMonth").addEventListener("click",()=>{state.current=new Date(YEAR,(state.current.getMonth()+1)%12,1);renderAll()});$("downloadIcs").addEventListener("click",downloadICS);$("closeDialog").addEventListener("click",()=>$("detailDialog").close());$("detailDialog").addEventListener("click",e=>{if(e.target===$("detailDialog"))$("detailDialog").close()});renderAll()}
init().catch(err=>{$("calendar").innerHTML=`<p class="empty">${esc(err.message)}</p>`});
